platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Hera' do
    
    workspace 'HeraDemo'
    xcodeproj 'Hera.xcodeproj'
	
    pod 'Reachability'
    pod 'MJRefresh'
    pod 'ZipArchive'
    pod 'AFNetworking'
	
end

target 'HeraDemo' do
    
    workspace 'HeraDemo'
    xcodeproj 'HeraDemo.xcodeproj'
	
	pod 'Reachability'
    pod 'MJRefresh'
    pod 'ZipArchive'
	pod 'AFNetworking'
	
end
